### ISSUE TITLE
`loader-utils` is not declared as a dependency

### ISSUE THREAD

**Issue by jprichardson** [headfire94/package-json-cleanup-loader#2]
`loader-utils` needs to be a dependency. See: https://github.com/headfire94/package-json-cleanup-loader/blob/12c595b4b67367251f3e378592d90b64fc60cdba/index.js#L1 in https://github.com/headfire94/package-json-cleanup-loader/blob/master/package.json

**Comment by headfire94** [comment]
100%. Will do

**Comment by headfire94** [comment]
fixed https://github.com/headfire94/package-json-cleanup-loader/commit/e17d5b8972213da84528775cf73cb7715045496c
